# Generated by Django 4.0.1 on 2022-01-18 19:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='NigerianState',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_of_state', models.CharField(max_length=100)),
                ('number_of_local_governments', models.IntegerField()),
                ('range_of_population', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Governor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('state', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='states_api.nigerianstate')),
            ],
        ),
        migrations.CreateModel(
            name='DeputyGovernor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('governor', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='states_api.governor')),
                ('state', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='states_api.nigerianstate')),
            ],
        ),
    ]
