# Generated by Django 4.0.1 on 2022-01-19 04:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('states_api', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='deputygovernor',
            name='governor',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='deputy_governors', to='states_api.governor'),
        ),
        migrations.AlterField(
            model_name='governor',
            name='state',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='governors', to='states_api.nigerianstate'),
        ),
    ]
